services:
  postgres:
    image: postgres:18-alpine
    container_name: my-noodles-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: my_noodles
      POSTGRES_PASSWORD: my_noodles
      POSTGRES_DB: my_noodles
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U my_noodles -d my_noodles']
      interval: 5s
      timeout: 5s
      retries: 5

  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: my-noodles-otel-lgtm
    restart: unless-stopped
    ports:
      - '3030:3000'
      - '4317:4317'
      - '4318:4318'

volumes:
  postgres_data:
