packages:
  - 'apps/*'
  - 'libs/*'
  - 'packages/*'
  - 'configs/*'
  - 'devops/*'

minimumReleaseAge: 0

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  argon2: set this to true or false
  esbuild: true
  less: true
  nx: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true
